variable "avi_server"	{}
variable "avi_username"	{}
variable "avi_password"	{}
variable "avi_version"	{}
variable "cloud_name"	{}
variable "vs_name"	{}
variable "vs_fqdn"	{}
variable "vs_address"	{}
variable "api_static_fqdn" {}
variable "api_static_fqdn_ip" {}
variable "ingress_static_fqdn" {}
variable "ingress_static_fqdn_ip" {}
